# Generated by Django 5.1 on 2024-09-30 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.CharField(max_length=255)),
                ('num_floors', models.IntegerField()),
                ('total_energy_consumed', models.FloatField(default=0.0)),
                ('total_energy_cost', models.FloatField(default=0.0)),
                ('energy_consumption_score', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Compartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_energy_consumed', models.FloatField(default=0.0)),
                ('total_energy_cost', models.FloatField(default=0.0)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartments', to='audits.building')),
            ],
        ),
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('power_rating', models.FloatField()),
                ('usage_time', models.FloatField()),
                ('total_energy_consumed', models.FloatField(default=0.0)),
                ('total_energy_cost', models.FloatField(default=0.0)),
                ('compartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliances', to='audits.compartment')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyConsumptionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('building', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='audits.building')),
            ],
        ),
    ]
