# Generated by Django 5.1 on 2024-09-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergySavingRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('HVAC', 'HVAC Optimization'), ('Lighting', 'Lighting Efficiency'), ('Appliance', 'Appliance Management'), ('Natural', 'Natural Cooling')], max_length=20)),
                ('recommendation', models.TextField()),
            ],
        ),
    ]
